In [2]:
import numpy as np


In [12]:
arr = np.random.randint(20,100,30)
arr =arr.reshape((5,6))
print(arr)

[[30 52 84 59 95 88]
 [53 60 22 85 90 27]
 [93 70 55 80 89 22]
 [41 49 53 83 73 78]
 [94 71 28 82 57 86]]


In [18]:
# sum of elements
print(arr.sum())
print(arr.mean())   # mean
print(np.median(arr)) # median
print(3* np.median(arr) - 2* np.mean(arr)) # mode

1949
64.96666666666667
70.5
81.56666666666666


In [21]:
a1 = np.random.randint(2,50,10).reshape(2,5)
print(a1)
a2 = np.random.randint(2,50,10).reshape(2,5)
print(a2)
print(a1 + a2) # simple addition

print(a1 * a2) # simple mul

[[13 31 39 21 11]
 [10 49 24 15 40]]
[[ 8 14 10 31 30]
 [ 2 32 16  3 18]]
[[21 45 49 52 41]
 [12 81 40 18 58]]


In [23]:
#matrix multiplication
a2 = a2.reshape((5,2))
print(a1.dot(a2))

[[2289 1755]
 [1890 2667]]


In [27]:
arr = np.random.randint(20,100,25)
arr =arr.reshape((5,5))
print(arr)
print(np.trace(arr)) # trace (sum of diagonal element)

print(np.linalg.det(arr))

[[59 98 49 95 44]
 [30 44 50 42 92]
 [40 30 46 77 47]
 [72 24 38 26 49]
 [96 78 90 42 25]]
200
1034641311.9999968


In [35]:
# 2x + 3y  = 7
# 7x - 2y = 9

A = np.array([[2,3],[7,-2]])
B= np.array([7,9])
# X= (A-1).B

inv = np.linalg.inv(A)
X= inv.dot(B)
print(X)

#alternate method
print(np.linalg.solve(A,B))

[1.64 1.24]
[1.64 1.24]


In [39]:
arr = np.random.randint(20,100,25)
arr =arr.reshape((5,5))
print(arr)
print(np.where(arr == 30))

[[81 47 98 62 60]
 [31 41 66 62 21]
 [65 30 36 52 27]
 [21 78 35 37 80]
 [97 93 37 84 91]]
(array([2], dtype=int64), array([1], dtype=int64))


# Pandas

In [40]:
import pandas as pd


In [42]:
l = ["Rohan","Sohan","Gita","Sita"]
df = pd.Series(l)
print(df)

0    Rohan
1    Sohan
2     Gita
3     Sita
dtype: object


In [43]:
d= {"name":["Rohan","Sohan","Gita","Sita"],
       "Age":[18,17,20,22]}
df= pd.DataFrame(d)
print(df)

    name  Age
0  Rohan   18
1  Sohan   17
2   Gita   20
3   Sita   22


In [44]:
# describe
print(df.describe())

             Age
count   4.000000
mean   19.250000
std     2.217356
min    17.000000
25%    17.750000
50%    19.000000
75%    20.500000
max    22.000000


In [53]:
name = df.iloc[1,[0,1]]
print(name)

name    Sohan
Age        17
Name: 1, dtype: object


In [55]:
name = df.loc[:, ['name','Age']]
print(name)

    name  Age
0  Rohan   18
1  Sohan   17
2   Gita   20
3   Sita   22


In [56]:
df.columns

Index(['name', 'Age'], dtype='object')

In [58]:
#update value
df.loc[1,:] = ["mohan",20]
print(df)

    name  Age
0  Rohan   18
1  mohan   20
2   Gita   20
3   Sita   22


In [59]:
df.loc[[1,2],:] = [["mohan",20],['Rita',19]]
print(df)

    name  Age
0  Rohan   18
1  mohan   20
2   Rita   19
3   Sita   22


In [62]:
#agregate function
df.iloc[:,1].aggregate(['min','mean'])

min     18.00
mean    19.75
Name: Age, dtype: float64

In [68]:
# #fillna method
# df.iloc[1,'Age'] = 
# print(df)

In [70]:
#read data from csv file
csv = pd.read_csv(r"C:\Users\DELL\Desktop\data.csv")
csv

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [75]:
csv.loc[:,['Duration','Pulse']].head(10)


Duration  Pulse
0        60    110
1        60    117
2        60    103
3        45    109
4        45    117
5        60    102
6        60    110
7        45    104
8        30    109
9        60     98

In [73]:
csv.tail(10)

Duration  Pulse  Maxpulse  Calories
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [77]:
excel = pd.read_excel("../student.xlsx")
excel

0                              1  \
0                    Name                          Email   
1             Aamash Alvi         aamashalvi01@gmail.com   
2              humra khan         khanhumra024@gmail.com   
3            Umair Kidwai        umairkidwai88@gmail.com   
4       Abhash Srivastava           abhashsr18@gmail.com   
5            Ailya Fatima    ailyafatima572022@gmail.com   
6          Prashant Singh   babusahab.prashant@gmail.com   
7         Nishant Jaiswal         jaiswalnj075@gmail.com   
8             Shreya null    shreya.singh16oct@gmail.com   
9           Garima Chawla     chawlagarima1909@gmail.com   
10          Harshita Rana     harshitarana1102@gmail.com   
11             Anmol null       anmolsandy1977@gmail.com   
12            Kajal Singh     tanu.sikarwar.77@gmail.com   
13            Kajal Singh     tanu.sikarwar.77@gmail.com   
14  Avishek  Vikram Singh         alphaman1711@gmail.com   
15        Subhan Siddiqui  subhansiddiquiiiiii@gmail.com   
16         Anupreet Singh         realanupreet@gmail.com   
17    naga_polisetty null          nagasai1602@gmail.com   
18        mohammad faisal  mohammadfaisal95111@gmail.com   
19          MOHD SARFARAZ     mohdsarfaraz1306@gmail.com   
20         Ishita Jaiswal  abhigyanvikramsingh@gmail.com   
21                    S k     ishitajaiswal976@gmail.com   
22      Priyam Srivastava         sasikiran060@gmail.com   
23            Rafid Hasan             gpps0618@gmail.com   
24            Bibhu Singh            hrafid001@gmail.com   
25            Abhay Yadav         singhbibhu04@gmail.com   
26       Aryan Srivastava            ay8873127@gmail.com   
27            Ahad Rehman         aryansri1607@gmail.com   
28           saurabh Vedi         ahadrehman33@gmail.com   
29           saurabh Vedi      saurabh.vedi777@gmail.com   
30           saurabh Vedi      saurabh.vedi777@gmail.com   
31           saurabh Vedi      saurabh.vedi777@gmail.com   
32           saurabh Vedi      saurabh.vedi777@gmail.com   

                           2                         3                    4  \
0                 Start Time                  End Time  Alice Rotates Array   
1   2024-01-19T09:00:06.562Z  2024-01-19T10:30:00.000Z                    0   
2   2024-01-19T08:46:10.506Z  2024-01-19T10:13:09.239Z                   80   
3   2024-01-19T08:46:17.155Z  2024-01-19T09:46:17.922Z                    0   
4   2024-01-19T08:47:43.730Z  2024-01-19T09:58:37.342Z                  100   
5   2024-01-19T08:46:08.925Z  2024-01-19T09:55:12.740Z                    0   
6   2024-01-19T08:46:36.962Z  2024-01-19T09:26:18.632Z                    0   
7   2024-01-19T08:46:36.530Z  2024-01-19T10:06:44.650Z                   80   
8   2024-01-19T08:46:42.359Z  2024-01-19T10:12:58.116Z                    0   
9   2024-01-19T08:46:51.238Z  2024-01-19T10:07:35.597Z                  100   
10  2024-01-19T08:46:12.715Z  2024-01-19T10:07:55.234Z                   80   
11  2024-01-19T08:46:15.179Z  2024-01-19T09:54:09.657Z                    0   
12  2024-01-19T08:46:15.085Z  2024-01-19T10:16:15.085Z                    0   
13  2024-01-19T08:46:15.102Z  2024-01-19T10:05:48.685Z                    0   
14  2024-01-19T08:45:57.423Z  2024-01-19T10:06:59.320Z                  100   
15  2024-01-19T08:46:17.780Z  2024-01-19T09:47:33.837Z                    0   
16  2024-01-19T08:47:23.514Z  2024-01-19T09:53:21.313Z                   80   
17  2024-01-19T08:45:28.976Z  2024-01-19T10:00:18.388Z                    0   
18  2024-01-19T08:45:38.777Z  2024-01-19T09:15:44.566Z                    0   
19  2024-01-19T08:46:36.332Z  2024-01-19T10:16:36.332Z                    0   
20  2024-01-18T15:14:13.133Z  2024-01-18T18:14:13.133Z                    0   
21  2024-01-19T08:46:20.324Z  2024-01-19T10:02:37.169Z                  100   
22  2024-01-19T08:46:49.375Z  2024-01-19T09:43:18.584Z                    0   
23  2024-01-19T08:47:48.529Z  2024-01-19T10:00:10.703Z                    0   
24  2024