In [2]:
import numpy as np



In [3]:
# help(np)

In [7]:
# numpy array
l= [1,2,3,4,5,6,7]
print(type(l))

arr = np.array(l)
print(type(arr))
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [9]:
#dimension
print(arr.ndim)
l = [[1,2,3],[4,5,6]]
arr2 = np.array(l)
print(arr2.ndim)

1
2


In [11]:
#shape
print(arr.shape)
print(arr2.shape)

(7,)
(2, 3)


In [12]:
#indexing of 1-dim
print(arr[2])

3


In [13]:
#indexing of 2-dimn
print(arr2[1,2])

6


In [14]:
print(arr2[:,1])

[2 5]


In [15]:
print(arr2[:,0:2])

[[1 2]
 [4 5]]


In [19]:
arr2= np.array([[1,2,3],[5,6,7],[8,9,10]])
arr3 = arr2
arr3[:,2::-2] = arr2[:,0::2]
arr3[:,1::2] = arr2[:,1::2]
print(arr3)

[[ 3  2  1]
 [ 7  6  5]
 [10  9  8]]


In [25]:
# for loop in numpy
arr1= np.array([1,2,3,4,5])
for i in arr1:
    print(i,end=" ")

# print(arr1.size)
print()
for i in range(arr1.size):
    print(arr1[i],end=" ")

1 2 3 4 5 
1 2 3 4 5 

In [38]:
arr2= np.array([[1,2,3],[5,6,7],[8,9,10]])

# for i in arr2:
#     for j in i:
#         print(j,end=" ")
#     print()
for i in arr2:
    print(*i) # destructuring


1 2 3
5 6 7
8 9 10


In [34]:
#for loop using nditer
for i in np.nditer(arr2):
    print(i)

1
2
3
5
6
7
8
9
10


In [39]:
# for loop using ndenumerate
for i in np.ndenumerate(arr2):
    print(i)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((2, 0), 8)
((2, 1), 9)
((2, 2), 10)


In [45]:
t= (5,6,7)
arr = np.array(t,dtype='f')
print(arr.dtype)
print(type(arr))
print(arr)

float32
<class 'numpy.ndarray'>
[5. 6. 7.]


In [51]:
#creating array
arr = np.ones((2,3),dtype='i')
print(arr)

arr = np.zeros((2,3),dtype='i')
print(arr)

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [5]:
arr = np.zeros((5,5))
arr.fill(2)
print(arr)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [61]:
arr2= np.array([[1,2,3],[5,6,7],[8,9,10]])
x =arr2.mean(axis =0)
print(x)

[4.66666667 5.66666667 6.66666667]


In [7]:
#creating array with random value
arr = np.random.random((2,3))
print(arr*100)


[[43.22188634 37.2325236  93.14318529]
 [68.51796463  4.38818023 89.979039  ]]


In [66]:
x= np.random.randint(50,100,6)
print(x.reshape(2,3))

[[69 63 76]
 [67 94 55]]


In [67]:
#flatten
arr1 =arr.flatten()
print(arr1)

[0.88447802 0.55904108 0.13755705 0.38748629 0.10529512 0.13368767]


In [68]:
arr = np.arange(5,10,2)
print(arr)

[5 7 9]
